"""add Gym model and gym_id foreign keys

Revision ID: 01585ad6643b
Revises: ba31c1ecf37b
Create Date: 2026-05-12 15:05:30.050426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01585ad6643b'
down_revision = 'ba31c1ecf37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('is_outdoor', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_route_gym_id', 'gym', ['gym_id'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gym_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_session_gym_id', 'gym', ['gym_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gym_id')

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('gym_id')

    op.drop_table('gym')
    # ### end Alembic commands ###
