"""add photo and video to climb

Revision ID: 2a7a68d6b279
Revises: 32649fc82f87
Create Date: 2026-05-13 11:51:00.781675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7a68d6b279'
down_revision = '32649fc82f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_column('video_url')
        batch_op.drop_column('photo_filename')

    # ### end Alembic commands ###
