"""add style_tags to climb

Revision ID: 32649fc82f87
Revises: 66010c3dbb19
Create Date: 2026-05-12 19:57:09.230048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32649fc82f87'
down_revision = '66010c3dbb19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style_tags', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_column('style_tags')

    # ### end Alembic commands ###
