"""add session_type and discipline

Revision ID: 43bc2ee3ab63
Revises: 27cffb483e9f
Create Date: 2026-05-12 13:50:45.062096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bc2ee3ab63'
down_revision = '27cffb483e9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discipline', sa.String(length=20), nullable=True))

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('session_type')

    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_column('discipline')

    # ### end Alembic commands ###
