"""add image_filename to gym and route

Revision ID: 66010c3dbb19
Revises: 01585ad6643b
Create Date: 2026-05-12 19:15:26.114139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66010c3dbb19'
down_revision = '01585ad6643b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gym', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('route', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    with op.batch_alter_table('gym', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
